### PR TITLE
coords.pmat: fix tiling .from_map behavior

### PR DESCRIPTION
**Pull request by mhasself**
Re-enable the test for rectpix tiled case.  This required a lot of custom checking for the rectpix+tiled case... and when combined with the healpix checking, this was hard to read.  So I've also abstracted that away using the notion of "flatten" and "unflatten" for maps.  This affects healpix and rectpix.

### CODE REVIEW

**Comment by mhasself** [comment]
@iparask Please check if this fixes your tiled map issues.
@earosenberg Please verify this doesn't wreck your standard healpix use cases.

**Review by earosenberg — COMMENTED** [review]
Looks good on the Healpix side except for the above comment. I can try to address it / help out if needed

**Comment by iparask** [comment]
> @iparask Please check if this fixes your tiled map issues. 

It does not... I'm still getting the same error. I synced my branch with master and merged it with this branch in a tmp.

```
  File "/home/ip8725/.local/soconda_20241017/3.10/lib/python3.10/site-packages/sotodlib/mapmaking/ml_mapmaker.py", line 375, in transeval
    pmap.from_map(dest=tod, signal_map=map, comps=self.comps)
  File "/home/ip8725/.local/soconda_20241017/3.10/lib/python3.10/site-packages/sotodlib/coords/pmat.py", line 446, in from_map
    so3g.proj.wcs._ProjectionistBase.from_map(
  File "/scratch/gpfs/SIMONSOBS/env/20241017/soconda_3.10/lib/python3.10/site-packages/so3g/proj/wcs.py", line 321, in from_map
    signal_out = projeng.from_map(
RuntimeError: Tiling problem (index 13): Projector expects tile but it is missing.
```

**Comment by mhasself** [comment]
@earosenberg  Ok, I think I've made this a bit more flexible in flatten/unflatten.  Test cases to cover it.

@iparask Not sure if this will help your error... likely a live debug session will be in order.

**Comment by earosenberg** [comment]
Looks good to me, I'll approve and you and @iparask can decide how to proceed with the other issue. Only comment is that the `_get_hp_tile_list` function is no longer used anywhere; we may want to delete it.

**Review by earosenberg — APPROVED** [review]

**Review by iparask — APPROVED** [review]

**Comment by iparask** [comment]
> @iparask Not sure if this will help your error... likely a live debug session will be in order.

Let's arrange it then. I will approve the PR so that we can move forward.

**Pull request merged**
