### PR TITLE
Time constant

### PR DESCRIPTION
**Pull request by keskitalo**
Add time constant capability to `toast_so_sim.py`. This PR addresses #50 

The functional parts are based on code contributed by @kmharrington

### CODE REVIEW

**Comment by mhasself** [comment]
Are we waiting for @aamirmali 's review to merge this?  Sometimes he gets requested accidentally cause he's at the top of the list :)

**Comment by keskitalo** [comment]
We are. He requested this feature. I told him there was no hurry.

**Comment by keskitalo** [comment]
This branch fell behind master. I rebased it but now there is a conflict between `sotoddb` and `sotodlib`. Looking into it.

**Comment by keskitalo** [comment]
@aamirmali it would be good if you could look at the new operator and see if it has the features you need. With the master branch reorganization, it will become increasingly laborious to maintain this branch.

**Comment by keskitalo** [comment]
Merging this PR after private communication with @aamirmali .

**Pull request merged**
