### PR TITLE
Do not attempt to write out HWP angle when it is not available. Fix t…

### PR DESCRIPTION
**Pull request by keskitalo**
…ype conversion for intervals

### CODE REVIEW

**Comment by keskitalo** [comment]
`from_mask` looks great! Let me try adding that to this PR.

**Comment by mhasself** [comment]
Indexing mistake in my code block... should be:
```
       frame_flags = single_bit_flags[dataoff:dataoff+ndata].astype(int)
```

**Comment by keskitalo** [comment]
Thanks. The unit tests now pass with this, much cleaner code. I will merge once Travis confirms.

**Comment by keskitalo** [comment]
Hmm. Travis tests seem to have been failing for some time due to missing so3g package. Since the unit tests pass on `simons1`, I'll open an issue about Travis tests and merge this.

**Pull request merged**
