### PR TITLE
import bookbinder from a separate repo

### PR DESCRIPTION
**Pull request by guanyilun**
bookbinder has been managed in a separate repo: https://github.com/simonsobs/bookbinder. As discussed in data flow call, the plan is to manage it under sotodlib.

### CODE REVIEW

**Review by kmharrington — APPROVED** [review]
Glad to see this coming in. We'll eventually need to add bookbinder / imprinting into the `docs/` set. Probably going to have a whole data packaging section TBH. But that's an issue for later.

**Review by mhasself — CHANGES_REQUESTED** [review]
Please acknowledge @algadoreo in the commit message, as this is mostly his work.

**Comment by guanyilun** [comment]
Sorry! that's a good point - fixed now!

**Comment by tskisner** [comment]
There have been several PR (including this one) stalling out on the MPI tests.  We saw a similar problem with toast using github CI and MPI.  I'll implement the same fix in sotodlib shortly in a separate PR.

**Comment by guanyilun** [comment]
superseded by #337

**Pull request closed without merging**
