### PR TITLE
fixed a wrapping bug with wiregrid.py

### PR DESCRIPTION
**Pull request by hnakata-JP**
I fixed a wrapping issue about the function of correct_wg_angle. Please check it and merge this into master.

### CODE REVIEW

**Comment by hnakata-JP** [comment]
This is a temporal pull request. If PR #820 will soon be merged into the master branch, this is not required any longer.

**Comment by hnakata-JP** [comment]
Thanks for your review, Matthew. I inserted an unwrap method before the averaging. Also, I adjusted the name of the functions to PR #820. If there are any other critical concerns, I will merge this in a day or two.

**Comment by mhasself** [comment]
> I inserted an unwrap method before the averaging

That's a decent start but please check:
- what does unwrap do, if there are nans?
- is the final result guaranteed to be in the range you want (previously it was guaranteed to lie in [0, pi], but now it is not).

**Comment by hnakata-JP** [comment]
Thanks for the comments. Basically, we need to provide the calibration angles within [0, pi]. I adjusted that.
And np.unwrap is safer than just using mod np.pi. Then, I combined the unwrap function and corrected with returning angles in the expected range.
Further, the documentation is not the scope of this pull request, but I added a temporal documentation though.

**Pull request merged**
