### PR TITLE
Modify planet mapmaker

### PR DESCRIPTION
**Pull request by yoshinori-0778**
Added xi/eta offset in get_scan_q in planets.py in order to take into account off-centered UFMs/detectors.
I only added those offsets so that this version has backward compatibility.
Demonstrations/Discussion using Jupiter observation for satp3 that having dipole T2P leakage from p.6 in https://docs.google.com/presentation/d/1H1T2U94in_STM8gw5q5HR3xolJYrKs4FQfjjAyozsLw/edit?usp=sharing.

### CODE REVIEW

**Review by mhasself — CHANGES_REQUESTED** [review]
Sorry to be slow to get to this.  Thanks for the useful extension.

Instead of `xioff, etoff`, please make this a single argument called `boresight_offset`, with default None.  The code may assume it's either None, or a (xi, eta) tuple.

Then rebase and force push the branch.

**Comment by mhasself** [comment]
> Thank you for your comment. Because I am not familiar with git so far, I would like to clarify what should I do by following your comment "Then rebase and force push the branch" .
> 
>     1. modify the script based on your comment("boresight_offset")
> 
>     2. add and commit to the branch "modify_planet_mapmaker"
> 
>     3. `git rebase master modify_planet_mapmaker`
> 
>     4. `git checkout modify_planet_mapmaker`
> 
>     5. `git push --force-with-lease origin modify_planet_mapmaker`
> 
> 
> These are my understanding. Is this correct?

I think what you post above is correct, except that step 4 would normally be unnecessary (i.e. you should still be on that branch, and you won't have to check it out again).

I would do this, which I believe is equivalent:
1. make your changes
2. add and commit to the branch "modify_planet_mapmaker"
3. `git fetch` (to update the local understanding of `origin/master`)
4. `git rebase origin/master`  (no additional args needed if you're still on the modify_planet_mapmaker branch
5. `git push --force` (no additional args needed, usually... but make sure you're on the `modify_planet_mapmaker` branch!)

**Comment by yoshinori-0778** [comment]
Thank you for your comments!
I followed what you suggested.

**Comment by yoshinori-0778** [comment]
Thank you for additional comments.
I reflected your comments, "PEP-8 format" and "squash".

**Review by mhasself — APPROVED** [review]
Great!

**Pull request merged**
