### PR TITLE
Have update_hwp_angle find it's own files.

### PR DESCRIPTION
**Pull request by kmharrington**
I've changed around the update hwp angle script to make it find it's own files instead of just running on a single file. The script looks through the `data_dir` and compares the file names to the `output_dir`. All existing files except the last one are assumed to have been complete and ignored. 

I tested this as data was actively coming in for P10r1, so I think this is a stable enough solution for now. 

I have a new config file shared at `/mnt/so1/shared/site-pipeline/data_pkg/p10r1/update_hwp_angle.yaml` and updated in the docs. This might break some of the usages in `G3tHWP` but I don't _think_ it will break how people have been interactively using it. 

@yukisakurai  could you please make sure I didn't do anything stupid? Will this still work for you?

@guanyilun  I think this is good enough to start trying to run it off prefect for p10r1.

### CODE REVIEW

**Comment by guanyilun** [comment]
Thanks! I have wrapped it as a flow here: https://github.com/simonsobs/so-workflow/pull/8/files and will test when this is merged.

**Review by mhasself — APPROVED** [review]
Consider os.makedirs instead of os.mkdir!

Thanks, have fun.

**Comment by yukisakurai** [comment]
Thank you for your excellent work. I have tested this branch script locally and this work fine for me.
I will try to update the docs with different PR.

**Review by yukisakurai — APPROVED** [review]
Thank you for your excellent work. I have tested this branch script locally and this work fine for me. I will try to update the docs with different PR.

**Pull request merged**
