### PR TITLE
Flag sso

### PR DESCRIPTION
**Pull request by keskitalo**
Add a facility to flag solar system objects. For example `--flag-sso Jupiter,30` will flag 30 arc minutes around Jupiter everywhere in the data. Multiple instances of `--flag-sso` are allowed and, notably, `Sun` and `Moon` are supported.

### CODE REVIEW

**Comment by Zhilei** [comment]
Looks great! I am curious to know how the functions are called from a higher scope.

**Comment by smsimon** [comment]
Are multiple units supported for the radius of the flagging (e.g. arcmin vs. degrees)? I could see needing to convert degrees into arcmin for larger radii as potentially annoying (but not hard to do).

**Comment by keskitalo** [comment]
@smsimon 

> Are multiple units supported for the radius of the flagging (e.g. arcmin vs. degrees)? I could see needing to convert degrees into arcmin for larger radii as potentially annoying (but not hard to do).

I can only support one unit on the command line. TOAST3 uses astropy units so we can revise this when we port it.

**Review by smsimon — APPROVED** [review]

**Comment by smsimon** [comment]
Sounds good

**Comment by aiolasimone** [comment]
Sorry to sneak into the conversation, but I have a question. 
Is it possible to dump the cut flags to a file and interface those with the Flag Manager (that @kmharrington developed)? I think those are useful if for example we want to map the plant TODs with the SO planet mapper or even the ML one.

**Comment by tskisner** [comment]
I think the eventual flow would be:

- Simulation creates toast observations in memory, including data ranges and flags
- Simulated data (including flags) is written to G3 files
- OR simuated data can be passed directly to other tools (map maker, wrapped "low-level processing")
- G3 files on disk (simulated or real) can be loaded into AxisManager and friends
- AxisManager data can be passed to low-level tools and anything working with that representation
- OR AxisManager data can be converted to toast observations and passed to map maker, wrapped low-level processing

**Comment by aiolasimone** [comment]
I agree, I think that would cover the spectrum of possible uses.

**Pull request merged**
