### PR TITLE
Adding the Correct Treatment of Temperatures

### PR DESCRIPTION
**Pull request by Zhilei**
Associated with issue #113

### CODE REVIEW

**Comment by mhasself** [comment]
Let's continue discussions from #113 here.

**Comment by Zhilei** [comment]
Great, discussion continuing!

**Review by mhasself — COMMENTED** [review]
Math looks right.  For style and organization in the toast submodule, I defer to @keskitalo .

However... what guide are you following for the docstring formatting?  I don't think "Input" is a header recognized by [sphinx-napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections)... use "Args", "Arguments", "Params", or"Parameters", e.g. see [other sotodlib docstrings](https://github.com/simonsobs/sotodlib/blob/6d82e92261b7ec8cc7db8f55fe6842da41cfb399/sotodlib/coords/helpers.py#L303
).

**Comment by Zhilei** [comment]
Great! Thanks @mhasself !
I was not following any specific convention just my personal habit. I have changed the docstring to follow the sotodlib, please feel free to take a look.

**Comment by Zhilei** [comment]
I was wondering whether we have more suggestions on this. Otherwise, I will merge probably today or tomorrow.

**Pull request merged**
