### PR TITLE
Adding first draft of single obs detdb

### PR DESCRIPTION
**Pull request by jseibert575**
Adding first draft of some code to generate a DetDb for a single observation. There's a lot of hard-coded values right now and need to make a variety of improvements to the code for modularity and user-friendly features, but the primary goal of generating a single-obs level DetDb seems to be working. I also don't think this should live in load_smurf but uses some of the functions defined within the module that are useful for now and I'm not sure what the longterm plan is for some of these.

### CODE REVIEW

**Comment by kmharrington** [comment]
This worked for me with some CalDbs except for some tweaks to the naming (which might be a slightly larger question than this, I just started following the first light pipeline ICD with the CalDbs I was testing but have previously called things ruids. tbh I'm indifferent on names but we should get them standardized). 

Apologies for just merging this into a different branch, yes I'm excited to have to untangle the git here later: https://github.com/simonsobs/sotodlib/blob/0d6d52b526004a28c17923d7466b33b9e79e555f/sotodlib/io/load_smurf.py#L1130 

I was able to use it like this: 
```
my_id = obs_list[2]['obs_id']
request = context.get_obs( obs_id=my_id, logic_only=True )
print(request['request'])

detdb = ls.make_DetDb_single_obs(context.obsfiledb, my_id, 'temp_det_db.db')
context.detdb = detdb
context.reload()

meta = context.get_meta(request['request'])
```

A couple notes / questions / paths for more development.

1. It is possible to get to the readout ids without ever opening a file. you can query tunesets from the observations table  (or perhaps its a query to the "association_obs" table) and then use the detsets association table to pull out the readout_ids/channel properties. I'm probably missing something but I don't think the core context obsdb / obsfiledb interfaces have this path (although if they don't I now think they should). But this is specific to g3tsmurf so I think it's legit to depend on that setup.
2. The "saving" step of adding the 880 channels here takes many seconds. This might be more for @mhasself  since you're just calling his functions but if we need to do this every time we want to load an observation it's too much overhead at the moment. There's probably a way to do this as a batch?
3. It would be cool to not have to pass in a file path, as I was changing the column names I learned I had to keep deleting the file in order make it work.

**Comment by kmharrington** [comment]
So these new updates are now fast / nice. Is there any reason we can't merge this now? I am a fan.

**Comment by jseibert575** [comment]
It’s been working fast for me. I’m happy to merge it and keep updating it just as I clean it up and add some more information. Working on PR now to build the loading directly into Context. 

I actually have one commit I’d like to add before merging, in that vein. I will commit that in one second.

**Comment by jseibert575** [comment]
It’s been working fast for me. I’m happy to merge it and keep updating it just as I clean it up and add some more information. Working on PR now to build the loading directly into Context. 

I actually have one commit I’d like to add before merging, in that vein. I will commit that in one second.

**Comment by jseibert575** [comment]
Sorry for the massive wave of commits, this branch was pretty far behind some commits that fixed a bunch of pep8 things that screwed things up i think? But those should be gone now

**Review by kmharrington — APPROVED** [review]

**Comment by mhasself** [comment]
Let's clean up the commit history on this before merging.

**Comment by jseibert575** [comment]
There's enough conflicts here that are all reformatting that I'm just going to close this PR and open a new one with a new branch based on the current version of master, with the updates.

**Pull request closed without merging**
