### PR TITLE
Instrument model revisions

### PR DESCRIPTION
**Pull request by smsimon**
In progress draft of updated instrument design.

Current revisions:

- removed sinuous detectors at MF
- changed MFF wafer type to MF
- changed SAT numbering and frequency mapping to match instrumentalists (SAT1-2 MF, SAT3 UHF, SAT4 LF)

### CODE REVIEW

**Comment by smsimon** [comment]
Added new fields and default values for readout studies

**Comment by smsimon** [comment]
Changed "wafer" field to "wafer_slot" and "wafers" to "wafer_slots" to clarify that these are slot names, not actual wafer names. Added a field to "wafer_slots" called "wafer_name" where the name of the current wafer in the slot can be added, default is blank.

**Comment by smsimon** [comment]
Changed "cards" fields to "card_slots", "card" to "card_slot", "crates" to "crate_slots". Added field "crate_name" in "crate_slots", "detector_name" in "detectors", and "card_name" in "card_slots" to enable putting the name of hardware items that are in the hardware slot. Changed numbering of "crate_slots" to be double digits.

**Comment by smsimon** [comment]
Changed band labels from "LF1, LF2, MFF1, MFF2, UHF1, UHF2" to "f030, f040, f090, f150, f230, f290" to better indicate frequencies. Naming convention consistent with detector group preference.

**Comment by smsimon** [comment]
All initial naming conventions and critical instrument updates included. Future updates may include a few more naming convention modifications and small enhancements/modifications (e.g. array clocking, full bandpass vs. tophat, etc.)

**Comment by keskitalo** [comment]
Should we squeeze the LAT boresight rotation into this branch as well?

**Comment by smsimon** [comment]
Yes, definitely add it in

**Review by keskitalo — APPROVED** [review]
Looks great. Merge away at your leisure!

**Pull request merged**
