### PR TITLE
context: bug-fix recent det_info changes

### PR DESCRIPTION
**Pull request by mhasself**
Oops, should put that det_info into aman.det_info, not into root level.

### CODE REVIEW

**Comment by kmharrington** [comment]
This gets us to `detset` and `detset_book` being in `aman.det_info`. That also seems confusing, those two fields had better be identical and if they aren't we have massive traceability problems.

**Comment by mhasself** [comment]
> This gets us to detset and detset_book being in aman.det_info. That also seems confusing, those two fields had better be identical and if they aren't we have massive traceability problems.

Ya, it's not my favorite to have them there.  I will drop _book, and replace it with some internal consistency check in the loader. 

> `detset_book` and `stream_id` are also not explicitly along the dets axis.

I don't understand what you mean.

**Comment by kmharrington** [comment]
When I print the AxisManager it said (for example) `stream_id[64]` instead of `stream_id[dets]` that means it's not assigned to the `dets` axis.

**Comment by mhasself** [comment]
> When I print the AxisManager it said (for example) `stream_id[64]` instead of `stream_id[dets]` that means it's not assigned to the `dets` axis.

I did not think that could possibly have happened!  Working on it...

**Review by kmharrington — APPROVED** [review]
Approving this because the two things I wanted to change I just went in and changed. @mhasself definitely double check my changes but I think we've mostly talked about them.

**Comment by mhasself** [comment]
Thanks!

**Pull request merged**
