### PR TITLE
Remove obs-id from tags

### PR DESCRIPTION
**Pull request by kmharrington**
Fix https://github.com/simonsobs/sotodlib/issues/916

### CODE REVIEW

**Review by BrianJKoopman — CHANGES_REQUESTED** [review]
This removes the 'observation' tag, but `record_tuning()` and `record_timing()` are going to still check for the `obs_id` in these tags. They do that with `monitor.check()`:
https://github.com/simonsobs/sotodlib/blob/1e08ce151864b6b709716bf60a2bb6be0996871d/sotodlib/site_pipeline/update_g3tsmurf_db.py#L148-L156

There must be a higher order tracking of which observations have already been processed by the site pipeline, yeah? This `monitor.check()` was meant to be used to avoid recomputing stats that were being monitored, the idea being that the `check()` could be used before the computation.

If there's some external tracking of this then I'm not really worried about accidentally re-writing the InfluxDB constantly. In either case, these checks also need to be removed, since they'll no longer function properly without the `observation` tags.

**Comment by kmharrington** [comment]
This is level 2 observation building so the tracking here isn't that simple because the code can't know in advance how many observations there should be or if the ones it's finding are supposed to be complete. It marks completed observations by setting `obs.stop` but that's it. 

After thinking about the setup more, I think I'm just going to pull the monitor off of this script and raise errors instead. I was already doing it with timing so adding the readout ids is easy. Bookbinding also fails when it encounters these situations so we weren't really using this data anyway. 

The monitor implementation in `update_book_plan` is definitely a much better implementation and we run alerts off of that one.

**Review by BrianJKoopman — CHANGES_REQUESTED** [review]
> After thinking about the setup more, I think I'm just going to pull the monitor off of this script and raise errors instead. I was already doing it with timing so adding the readout ids is easy. Bookbinding also fails when it encounters these situations so we weren't really using this data anyway.

That's fine by me. There are some lingering monitor related options, one pointed out in line below. The other is the `--use-monitor` argument setup in argparse on [lines 129-130](https://github.com/simonsobs/sotodlib/blob/7177b42aa2c3ac39d782b9b37277fa1eb277cbb2/sotodlib/site_pipeline/update_g3tsmurf_db.py#L129-L130). That should be dropped too.

If this is being dropped, does that mean we can drop the `g3tsmurf` measurement when we clean things up in the InfluxDB at site too?

**Review by BrianJKoopman — APPROVED** [review]
Looks good! Thanks for the changes.

**Pull request merged**
