### PR TITLE
G3thwp nan fix

### PR DESCRIPTION
**Pull request by ykyohei**
There were hwp angle nan issues in the observations that the hwp stopped in the middle of observations. https://github.com/simonsobs/sotodlib/issues/966
This is because the old hwp angle extrapolation method returns nan when the data range of hwp angle is shorter than the range of observation. This PR improves the hwp data extrapolation methods in general and resolves the nan issue.
This PR also improves the logging of hwp solution pipeline.

This PR does not change the pipeline output except for edge cases, so I do not plan to update the version of hwp_angles metadata.

### CODE REVIEW

**Comment by 17-sugiyama** [comment]
I guess the extrapolation runs e.g. when the hwp data is shorter than the observation data.
How do you think of adding the extrapolated indexes to the filled_flag?

**Comment by 17-sugiyama** [comment]
I'm sorry if I'm misunderstanding, but I guess the extrapolation of `filled_flag` fills with False where hwp data is extrapolated.
How do you think of filling `filled_flag` with True instead? Extrapolation is similar to fixing packet drops.
https://github.com/simonsobs/sotodlib/blob/cb51d0c53a99dedf7835d9c64509be9a3014bfc5/sotodlib/hwp/g3thwp.py#L1030C1-L1033C81

**Comment by ykyohei** [comment]
@17-sugiyama That sounds good. Updated bool interpolation.

**Review by 17-sugiyama — COMMENTED** [review]
Looks very nice!

**Review by 17-sugiyama — APPROVED** [review]

**Pull request merged**
