### PR TITLE
Imprinter: add support for timing system and its fallback

### PR DESCRIPTION
**Pull request by guanyilun**
This PR includes various small changes to imprinter to work with the timing updates. This completes the last missing piece of #357. Also fixes point 4 in #388.

### CODE REVIEW

**Review by kmharrington — COMMENTED** [review]
What I see here looks good but I think I'm missing part of it. How does setting `book.timing = False` in the exception lead to the books getting Rebound in a different way?

**Comment by guanyilun** [comment]
> What I see here looks good but I think I'm missing part of it. How does setting `book.timing = False` in the exception lead to the books getting Rebound in a different way?

Ah sorry for the confusion! Failed books will be automatically retried in the next run, so when it reruns it will be trying with timing=False.

**Review by kmharrington — APPROVED** [review]
Ok, great,  one new question. `REBIND` is saying "we have those books but we want to delete and re-write them." I am guessing that is something done for debugging / testing since we're fixing lots of things right now. If so, that's cool. 

But I want to make sure nothing is automatically tagging books as rebind and it's not something we plan to use in the field. Because "we will never remake books" once they've been passed off to the librarian is a pretty big tenant of the books.

**Comment by guanyilun** [comment]
> Ok, great, one new question. `REBIND` is saying "we have those books but we want to delete and re-write them." I am guessing that is something done for debugging / testing since we're fixing lots of things right now. If so, that's cool.
> 
> But I want to make sure nothing is automatically tagging books as rebind and it's not something we plan to use in the field. Because "we will never remake books" once they've been passed off to the librarian is a pretty big tenant of the books.

You are right - they are only a manual handle to remake books when there's some major non-compatible changes in bookbinder. I don't expect to use this much in production, unless it's to resolve some specific failure mode. I've seen some failure mode where g3tsmurf db indexes files while Observations are being written to disk, which leads to Imprinter registering a book that's missing one wafer, in that case I expect to manually label them as rebind and let the imprinter maintanance bot (which runs daily) to handle those cases.

**Pull request merged**
