### PR TITLE
remove logger arg of the main function in site_pipeline scripts

### PR DESCRIPTION
**Pull request by guanyilun**
logger arg in main functions of each site_pipeline script is to provide a way to pass prefect logger into the script. Now we are using stream capture, so directly passing in logger is no longer required. Directly modifying function signature is also somewhat unstable. This PR is meant to go along with the incoming update in prefect wrapper: https://github.com/simonsobs/so-workflow/pull/33

### CODE REVIEW

**Comment by kmharrington** [comment]
Looking at the defaults for imprinter, this should be fine for update_book_plan, but I think I'd prefer to initialize the site-pipeline logger inside the site-pipeline scripts and send them to imprinter? doesn't have to come from prefect though.

**Comment by guanyilun** [comment]
> Looking at the defaults for imprinter, this should be fine for update_book_plan, but I think I'd prefer to initialize the site-pipeline logger inside the site-pipeline scripts and send them to imprinter? doesn't have to come from prefect though.

ok, I have added that back now!

**Review by mhasself — APPROVED** [review]
Looks fine to me; thanks.

**Comment by jlashner** [comment]
Currently it looks like if init_logger is called multiple times with the same name it will register the same handlers multiple times... can we add a check for this to prevent duplicate logs?

**Comment by mhasself** [comment]
> Currently it looks like if init_logger is called multiple times with the same name it will register the same handlers multiple times... can we add a check for this to prevent duplicate logs?

Good point.

Another problem is that simply importing a site_pipeline script will cause the logger to print to stdout, if `init_logger` is called on import (rather than, say, in the main function).

I think it might make more sense for the "scripts" in site_pipeline to declare their loggers in the usual library-like way at the top:
```
logger = logging.getLogger(__name__)
```
and then in the _main_ function, call `init_logger` or similar to add a handler that makes the local logger verbose.
```
def main(...):
    ...
    util.init_script_logger(logger, verbosity=verbosity)
```

This is a bit of work + testing so not sure if it goes in this PR.

**Comment by guanyilun** [comment]
> Currently it looks like if init_logger is called multiple times with the same name it will register the same handlers multiple times... can we add a check for this to prevent duplicate logs?

Is this a satisfactory solution to that?
https://github.com/simonsobs/sotodlib/pull/731/commits/4bc8b97a203526e2705661ce71779ea8153e2bbf

**Comment by jlashner** [comment]
I think this should be fine! this is typically what I do.

**Review by jlashner — APPROVED** [review]

**Pull request merged**
